### ISSUE TITLE
build error with c lib

### ISSUE THREAD

**Issue by sken77** [BLAKE3-team/BLAKE3#72] opened 2020-03-23 22:11 UTC
```
gcc -shared -O3 -o libblake3.so blake3.c blake3_dispatch.c blake3_portable.c \
>     blake3_sse41_x86-64_unix.S blake3_avx2_x86-64_unix.S blake3_avx512_x86-64_unix.S
/usr/bin/ld: /tmp/ccoz9HaM.o: relocation R_X86_64_PC32 against symbol `blake3_simd_degree' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```
I'm getting the error above when trying to compile the share library. including `-fPIC` solves it, but not sure if that will result in intended behavior. a small clarification on this would be good

**Comment by sneves** [comment] 2020-03-23 22:47
You'll need to specify the particular system (Linux (?) distribution, GCC version, at least) this is happening on. I cannot reproduce this.

**Comment by sken77** [comment] 2020-03-24 00:22
Sorry about that

```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

GCC is

```
ost=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
```

**Comment by sken77** [comment] 2020-03-24 00:33
also now that i have your attention
```
x86_64-w64-mingw32-gcc -I/usr/lib/jvm/default-java/include -I/usr/lib/jvm/default-java/include/linux -shared 
-o ../blake3.dll blake3.c blake3_dispatch.c blake3_portable.c blake3_sse41_x86-64_windows_gnu.S \ 
blake3_avx512_x86-64_windows_gnu.S
```

this should build a working dll for windows 64 right? I'm working on JNI bindings for the c api. so thats why i need to build the project in different platforms while appending the Java bindings

Thanks!

**Comment by sergeevabc** [comment] 2020-03-24 05:15
Could mere Windows users without compilers try this bleeding-edge stuff? Give us a binary, please.

**Comment by sneves** [comment] 2020-03-24 10:59
It would appear that on this GCC version, either `-fPIC` is not a default or `-shared` does not activate it automatically for the selected input files, even though it's necessary for linking to work. Adding `-fPIC` manually is an appropriate solution.

Regarding Windows, I am not too familiar with the MinGW toolchain, but you might need `dllexport` and `dllimport` annotations, like shown [here](http://www.mingw.org/wiki/sampleDLL). A DLL library was not something we explicitly targeted.

**Comment by sergeevabc** [comment] 2020-03-24 15:35
@sneves, what library? I talk about ```.exe```, generated as less dependent as possible. Like @Cyan4973 does with [xxHash][1].  Wider audience uses, as you know, Windows. And we’re still patiently waiting for a  SHA2/3 replacement, because BLAKE2 never achieved it (that is, screwed because of being too diverse).
 
[1]: https://github.com/Cyan4973/xxHash/releases

**Comment by sken77** [comment] 2020-03-24 17:18
@sneves i just tried it with gcc 7.4 and it resulted in the same error btw. strange

**Comment by sken77** [comment] 2020-03-24 19:37
@sneves i got it to compile a working dll with the following

```
x86_64-w64-mingw32-gcc -I/usr/lib/jvm/default-java/include -static -shared -o ../../../natives/windows_64/blake3.dll blake3.c blake3_dispatch.c blake3_portable.c blake3_sse41_x86-64_win
dows_gnu.S blake3_avx2_x86-64_windows_gnu.S blake3_avx512_x86-64_windows_gnu.S org_scash_NativeBLAKE3.c
```
it works with either `-static` or `-static-libgcc` without either of these the dll is trying to find `libgcc_s_seh-1.dll` which is the dll in charge of handling and throwing exceptions. I'm not very familiar with c. I found this by exploring the dll dependencies with the Dependency Checker for dlls.

It works now as in the library is successfully loaded into jvm. Testing the actually bindings is next. 

https://github.com/sken77/BLAKE3jni

here is a link of the project

**Comment by oconnor663** [comment] 2020-03-24 19:53
@sergeevabc, this issue is discussing a specific set of compiler errors. If you'd like to discuss pre-compiled binaries, please open a separate issue. (If you want to try out BLAKE3, I recommend taking a look at the `b3sum` binary, by installing the Rust toolchain and running `cargo install b3sum`. But if that doesn't work for you, again, please open a separate issue, to avoid taking this one off-topic.)

**Comment by oconnor663** [comment] 2020-03-24 20:00
@sken77 [tweeted](https://twitter.com/Blake3Team/status/1242541550044839938) :)

**Comment by oconnor663** [comment] 2020-04-03 14:39
It looks like the questions here have been answered, so I'm going to close this one. I've opened https://github.com/BLAKE3-team/BLAKE3/issues/78 about pre-compiled binaries.

**Closed** 2020-04-03 14:39 UTC
