### ISSUE TITLE
very high ram usage on 133GB file?

### ISSUE THREAD

**Issue by divinity76** [BLAKE3-team/BLAKE3#93] opened 2020-06-24 00:02 UTC
ran b3sum v0.3.4 64bit windows release, on a 143249768448 bytes file,  on a laptop with 16GB ram. b3sum allocated over 13GB ram while running, and my ram usage was at 99% (im guessing it allocated as much ram as it possibly could without swapping?), is that intended behavior?

edit: also i didn't pipe it in, i gave the filename as an argument to b3sum

b3sum: b3sum v0.3.4 64bit windows release from https://github.com/BLAKE3-team/BLAKE3/releases/download/0.3.4/b3sum_windows_x64_bin.exe
OS: win10 x64 version 1909
CPU: Intel Core i7-8565U, 4 cores, 4 threads (hyperthreading disabled)
RAM: 16 GB total, ~13GB available (2x8GB LPDDR3-2133)

**Comment by oconnor663** [comment] 2020-06-24 01:07
Are you sure `b3sum` actually allocated that space? Does it all go away when `b3sum` exits, or does utilization remain high? What `b3sum` is supposed to be doing is memory mapping the file, so the kernel should be using as much memory as possible to cache file pages. On Linux, I think that shows up as a lot of memory "in use" but still "available", which can be a source of confusion. It can look like the machine is low on RAM, when in fact the kernel is able to reclaim those available pages whenever it needs to. However, I don't know how these things get reported on Windows, so I don't know the right questions to ask here.

**Comment by divinity76** [comment] 2020-06-24 08:21
> Are you sure b3sum actually allocated that space?

looks like it (altho, given what you said, i guess it's just the OS allocating it on behalf of b3sum for memory mapping?) this is the system before starting b3sum: 
![image](https://user-images.githubusercontent.com/1874996/85520073-b751c280-b602-11ea-9e35-9cb8d34b0928.png)

and this is after b3sum has started:
![image](https://user-images.githubusercontent.com/1874996/85520882-c8e79a00-b603-11ea-864b-c67e835f0895.png)

> Does it all go away when b3sum exits, or does utilization remain high? 

yes it goes away, this is after b3sum has exited:
![image](https://user-images.githubusercontent.com/1874996/85521192-2da2f480-b604-11ea-9671-b78f077621ac.png)

**Comment by oconnor663** [comment] 2020-06-28 21:14
Hmm that is very suspicious. The `blake3` library crate itself does very little allocation. There shouldn't be anything besides whatever `memmap` does, and whatever the global `rayon` thread pool does. The `b3sum` binary does some bookkeeping on top of that, like parsing command line args, but that should also be pretty trivial. I wonder if memory mapping works differently on Windows than on Unix, in some surprising way that could cause this?

Is there any way you can debug what part of the program is consuming memory? I don't know what the usual approach is for Windows tooling, but a memory profile of this would of course be super informative.

One thing I'm curious to try is hashing the same file from stdin (using `<`). I'll be pretty surprised if the problem persists in that mode. (Though if it doesn't persist, it would still be ambiguous whether the culprit is Rayon or Memmap or something else.)

Another thing I'd be curious to try is keeping memory mapping on, but only using one thread, like this: `b3sum --num-threads=1`.

**Comment by sneves** [comment] 2020-06-29 15:19
This is just how Windows looks like with memory-mapped files. Mapped pages will factor into the working set size, even though they're not "real" memory allocated by the program:

    The working set of a process is the set of pages in the virtual address space of the process that are currently resident in physical memory.

So this is not a memory leak or anything, it's just the OS doing as it's expected to. The same happens in the Unices.

**Comment by oconnor663** [comment] 2020-06-29 15:31
Ok cool, closing as expected behavior. Thanks for the report though, @divinity76. This will be a useful reference for people who see the same thing in the future.

**Closed by oconnor663** 2020-06-29 15:31 UTC
