### ISSUE TITLE
question/help for checksum of collections and complex types

### ISSUE THREAD

**Issue by yuribudilov** [BLAKE3-team/BLAKE3#213] opened 2021-11-24 03:30 UTC
Hello everyone.
I hope this is the correct place to ask for "how to" best-practices help using this crate.

I would like to hash/checksum a large Rust collection of complex types.
(could be in tens of gigabytes in total, such as vector or btree/hash-map of enums of structs or tuples.

For example consider a Vec<enum_or_struct_or_tuple> or a BTreeMap<struct> of 10 million struct-like items.

I have used your documentation to make it work on small test case like so: (Rust code)

```
//  return Rust Type (struct/enum/tuple) as a byte slice reference
unsafe fn any_as_u8_slice<T: Sized>(p: &T) -> &[u8] {
    ::std::slice::from_raw_parts((p as *const T) as *const u8, ::std::mem::size_of::<T>())
}

// in main:
    let mut hasher = blake3::Hasher::new();
    for b in vstat.iter() { // collection iterator, loop
        let byteslice = unsafe { any_as_u8_slice(&b) }; //b is a struct, return &[u8]
        hasher.update(byteslice); // append to hasher
    }
    let hashresult = hasher.finalize();


```

could someone confirm above is the correct/recommended way of handling *large data structures* to hash/checksum large in-memory data collections?
I can use iterator to hash the BTreeMap<T> and HashMap<T> in a similar way as with Vec<T>

If above approach is not the best way, can anyone comment the recommended way of checksum/hash of large Rust data structures please.

Also, is this the best forum to ask how-to-best-practice questions regarding use of blake3 crate? 
Should I use Rust discord for these types of questions? 
I cross-posted the link to this question on discord Rust cryptography-and-security thread,
thank you.

**Comment by oconnor663** [comment] 2021-11-26 19:24
> I hope this is the correct place to ask for "how to" best-practices help using this crate.

Sure, no worries. We don't really have a forum other than this repo, and our issue traffic isn't too high in general. I'll go ahead and close the issue, since it's not a bug/feature/etc, but feel free to respond here with follow-up questions.

> `::std::slice::from_raw_parts((p as *const T) as *const u8, ::std::mem::size_of::<T>())`

There are several reasons you shouldn't convert objects to bytes like this:

- Many object types include uninitialized padding bytes. For example, `struct Foo { x: u32, y: u16 }` will _probably_ get laid out by the compiler as something like `struct Foo { x: u32, y: u16, _padding: u16 }` in order to guarantee that `Foo` objects in an array are always 4-byte "aligned". (The `u32` member requires this.) That anonymous `_padding` field is often uninitialized, and using uninitialized bytes (to print them, branch on them, hash them, etc.) is undefined behavior. There are many reasons we must never have any UB in our programs, but one of those reasons is that the apparent value of those uninitialized bytes will be "random", so the resulting hash is going to be inconsistent. Or the UB issue might just crash your whole program; the thing with UB is that it can do anything.
- The object layout of most Rust types (those that aren't `repr(C)` or `repr(transparent)`) is unstable and might change between compiler versions, between target platforms, or with different compiler flags. This is why I said "probably" in the bullet above. Even if we could guarantee that the padding bytes were e.g. initialized to zero, it _still_ wouldn't be correct to do this pointer cast, because we wouldn't have any guarantees about exactly which bytes were `x` and which were `y` and which were `_padding`. If the layout were to change -- and it's likely that it will over time -- our hashes would also change. That wouldn't be UB per se, but it would definitely be a correctness issue in our program.

The first bullet is always a serious issue. The second bullet might not be an issue if you know for a fact that your hashes will only be kept in memory, and never saved to disk or sent over the network. In that case, they only need to be consistent for the duration of one process, so maybe it's ok if they aren't consistent between different builds of the program. But hashes created for one use case do have a tendency to find new use cases over time, so this is risky from a longer-term security/maintenance perspective.

So what should you do instead. In general, you need to serialize your struct to bytes in some way that's known to be stable. The easiest way to do this is to start with something like `[0u8; 100]` (or whatever size you need) and explicitly write each field into the array. You'd convert integers to bytes with the `.to_le_bytes()` method or similar. (Integer endianness is yet another consistency issue we could worry about above, and asking explicitly for "be" or "le" bytes solves that issue.) Enums are a little trickier, because you don't have direct access to the "field" that tells you which variant the enum object is, so you'll need to make up a new field yourself to represent this. As long as you assign each field a consistent number, you'll get a consistent, unambiguous serialization. Then you pass your array to `hasher.update()` or similar.

> Side note \#1: If your types include data of variable length, like strings and vectors, this gets trickier. You need to make sure the _boundary_ between different fields is clear. This is often done with a length prefix. It can be hard to make sure you've done this right, though, especially if you're only ever hashing these arrays and not decoding them back into objects. If you do have an ambiguity issue, you might not notice.

> Side note \#2: If you only ever hash one type of object, this "custom byte array" approach is probably all you need. But if you hash _multiple_ different types, you need to ask more questions about whether values of two different types are allowed to give the same hash. (Similarly, arrays and slices of different types.) If you want a guarantee that the hashes of two different types will never collide, you'll need to find a way to guarantee that yourself in your array representation, probably by giving each type a different number and including that number in the array. Again, it's easy to overlook this, especially as new types are added over time. And if the set of all types you might hash is open, such that there's no way for you to give each type a number, it can be quite tricky to figure out what to do.

So anyway, yes, this "custom byte array" approach is good for simple cases, but it has its limitations. It's tempting to reach for an off-the-shelf serialization format like JSON or Protobuf, to save ourselves the trouble. Unfortunately, most common serialization formats aren't designed for this. For example, JSON serializers don't usually make stable guarantees about the order in which different fields appear, or about exactly which characters in strings get escaped. They also make opinionated choices that might not make sense for this use case. For example, JSON serialization includes the _name_ of each field, which might not be something you want to stabilize forever.

In general, "hashing an arbitrary object" is quite a tricky problem, which is pretty easy to solve for a one-off use case but very difficult to solve generically. The generic problem is about as difficult as defining a new serialization format to compete with JSON. It's something I'm interested in working on in the future, but not something I have a good solution for today. There have been a couple past discussions in other issues that you might be interested in:

- https://github.com/BLAKE3-team/BLAKE3/pull/87#issuecomment-647069248
- https://github.com/BLAKE3-team/BLAKE3/pull/100#issuecomment-663101211

**Closed** 2021-11-26 19:24 UTC

**Comment by yuribudilov** [comment] 2021-11-27 04:52
thank you very much! Much obliged.
